### ISSUE TITLE
algorithm bandwidth of all2all

### ISSUE THREAD

**Issue by de1star** [NVIDIA/nccl-tests#130]
Hi, thanks for your great help that solved my problem in another issue.   
I'd like to calculate the algorithm bandwidth of all2all on my cluster, but I found https://github.com/NVIDIA/nccl-tests/blob/master/doc/PERFORMANCE.md did not mention that. May I ask how to calculate it when knowing the bandwidth and number of IBs?

**Comment by sjeaugey** [comment]
The alltoall busBw bandwidth is simply computed by multiplying the AlgorithmBw by (n-1)/n, since 1/n of the data is local and (n-1)/n is remote.

If you have one GPU per node the BusBw should be the NIC BW.

On a system with both NVLink and NICs, then a portion of the traffic will be local (and should not be the bottleneck; the portion that's going through the network will determine the global time, hence the reported bandwidth.

On 2 nodes, 50% of the traffic is inter-node so you should see BusBW = 2x network bandwidth per GPU. As the number of nodes increases, it will go down to 1x the network bandwidth per GPU (general formula is N/(N-1)x the bandwidth per GPU, N being the number of nodes).

**Comment by de1star** [comment]
Thanks for your reply! @sjeaugey

**Comment by renwuli** [comment]
@sjeaugey 

Thanks for your explanation.

If we have M GPU per node, and each GPU is connected with one NIC, what should the busbw be for single node and multi nodes?

**Comment by sjeaugey** [comment]
This is running on just 2 GPUs so 100% of the traffic will go through the network. Hence you should expect a peak of 50GB/s.

And you're getting 47 up to 2G which seems good to me. I don't really understand why bandwidth dropped to half during the first 4G test though. Maybe some other workload started running and used half of the bandwidth?

**Comment by ltm920716** [comment]
hi
![Image](https://github.com/user-attachments/assets/216b20c4-e818-4bf2-b372-dea3a42825f3)

I run the test for another times，the bw not so stable，but the peak is ok

**Comment by ltm920716** [comment]
@sjeaugey
now I use 2 GPUs and two NICs each node ，the all2all result as bellow：
![Image](https://github.com/user-attachments/assets/9c18b401-ae4e-4944-9bd7-56755ceaa3c9)

so the busbw is the average of bw with nvlink（intra） and nic（inter）？and how could I calculate the NIC bw for this situation，thanks！
