### ISSUE TITLE
Why is all_reduce_perf result not consistent with that of reduce_scatter_perf and all_gather_perf?

### ISSUE THREAD

**Issue by EdwardZhang88** [NVIDIA/nccl-tests#19]
I am running nccl-test on my bare metal machines. I have set up RoCE and GPU Direct RDMA. As far as I know, the allReduce implementation in NCCL is a ring-based one, so theoretically the all_reduce_perf result should be in line with reduce_scatter_perf and all_gather_perf. However, in my case, when I set NCCL_IB_DISABLE=0 and NCCL_IB_CUDA_SUPPORT=1, the all_reduce_perf result is way worse than any of reduce_scatter_perf and all_gather_perf. How is that supposed to happen if an allReduce operation is made up of a reduceScatter and an allGather?
NCCL_IB_DISABLE=0 and NCCL_IB_CUDA_SUPPORT=1, GPU0 on node 1<-> GPU0 on node 2
all_reduce_perf result
<img width="789" alt="Screen Shot 2019-04-17 at 11 07 02 AM" src="https://user-images.githubusercontent.com/28944236/56258142-1d8aad80-6101-11e9-9ec5-4efe5df319d0.png">

reduce_scatter_perf 
<img width="761" alt="Screen Shot 2019-04-17 at 11 10 13 AM" src="https://user-images.githubusercontent.com/28944236/56258257-7b1efa00-6101-11e9-997a-49124d6f9e82.png">

all_gather_perf
<img width="713" alt="Screen Shot 2019-04-17 at 11 09 07 AM" src="https://user-images.githubusercontent.com/28944236/56258209-562a8700-6101-11e9-8ab8-60866aadcdfb.png">

Interestingly, when I turn off GPU Direct RDMA by setting NCCL_IB_DISABLE=0 and NCCL_IB_CUDA_SUPPORT=0, the all_reduce_perf result is even better than both reduce_scatter_perf and all_gather.
NCCL_IB_DISABLE=0 and NCCL_IB_CUDA_SUPPORT=0, GPU0 on node 1<-> GPU0 on node 2
all_reduce_perf result
<img width="762" alt="Screen Shot 2019-04-17 at 11 13 51 AM" src="https://user-images.githubusercontent.com/28944236/56258391-fe405000-6101-11e9-9e09-a55496d9558f.png">

reduce_scatter_perf 
<img width="775" alt="Screen Shot 2019-04-17 at 11 15 17 AM" src="https://user-images.githubusercontent.com/28944236/56258436-2d56c180-6102-11e9-9a7c-913192c1ad49.png">

all_gather_perf
<img width="712" alt="Screen Shot 2019-04-17 at 11 16 25 AM" src="https://user-images.githubusercontent.com/28944236/56258500-57a87f00-6102-11e9-9003-deaeff2cd5ee.png">

On top of the initial question, isn't GPU Direct RDMA supposed to speed up the communication? Is it because the GPU PCIe topology in my environment doesn't support GPU Direct RDMA  at all?
<img width="451" alt="Screen Shot 2019-04-17 at 11 19 10 AM" src="https://user-images.githubusercontent.com/28944236/56258594-a6561900-6102-11e9-8058-b3bbf4d0cd68.png">

**Comment by AddyLaddy** [comment]
In NCCL 2.4 onwards AllReduce is implemented using a tree up to a certain (computed) threshold.
You can disable this by setting `NCCL_TREE_THRESHOLD=0` which will force NCCL AllReduce to use rings. All the other NCCL collectives are implemented using Rings still, so maybe that explains the performance difference?

Are you using NCCL 2.4.x or an earlier release ?
Have you tried with NCCL 2.3.7 ?

I don't know why AllReduce is performing badly though or why GDRDMA is not better.
What is the performance like when all 4 GPUs per node are being used?

**Comment by EdwardZhang88** [comment]
Thanks for your reply! @AddyLaddy  
I am using NCCL 2.2.13. And 4 GPUs per node performance is
all_reduce_perf
<img width="765" alt="Screen Shot 2019-04-17 at 12 48 16 PM" src="https://user-images.githubusercontent.com/28944236/56261860-2aae9900-610f-11e9-90e0-b310095353ff.png">
all_gather_perf
<img width="701" alt="Screen Shot 2019-04-17 at 12 49 24 PM" src="https://user-images.githubusercontent.com/28944236/56261914-59c50a80-610f-11e9-85a5-803e6f306da8.png">
reduce_scatter_perf
<img width="757" alt="Screen Shot 2019-04-17 at 12 50 44 PM" src="https://user-images.githubusercontent.com/28944236/56261975-85e08b80-610f-11e9-8749-9eb4fc3c1b32.png">
The command I used is 
`mpirun -n 4 --mca btl ^openib --mca btl_tcp_f_exclude lo,docker0,tunl0 --hostfile hostfile -x NCCL_IB_DISABLE=0 -x NCCL_IB_CUDA_SUPPORT=1 -x NCCL_IB_HCA=mlx5_0 -x NCCL_SOCKET_IFNAME=eno2.100 -x NCCL_DEBUG=INFO all_reduce_perf -b 16M -e 1024M -f 2 -g 1 -c 0`
Do you think it would yield better result if I switch to NCCL 2.3 or 2.4?

**Comment by kwen2501** [comment]
GPU Direct RDMA will only speed up NCCL communication when the GPU-to-NIC distance is smaller than PHB (not included). It will be disabled by default with your PCI-E topology if you don't set `NCCL_IB_CUDA_SUPPORT` to anything. Also please note that this environment variable is replaced by `NCCL_NET_GDR_LEVEL` since NCCL 2.4, for details see https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/env.html#nccl-ib-cuda-support

NCCL 2.3 improves performance at small message size and NCCL 2.4 improves performance at large scale. If any of these two applies to your use case, you may get a performance gain.

Regarding the inter-node performance, what type of NICs do you have? What is their line rate?

Regarding intra-node performance, if you are using a AMD EPYC CPU or Intel Skylake, you can try if setting `NCCL_P2P_LEVEL=5` improves the performance. This environment variable, however, is only available after NCCL 2.3.4 (https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/env.html#nccl-p2p-level), and you might need some BIOS settings to enable P2P.

**Comment by EdwardZhang88** [comment]
Thanks for the detail reply! @kwen2501 
I am using 25Gb Mellanox ConnectX-4 Lx. CPU model is Intel Skylake.
I also suspected that GPU Direct RDMA might not work in my current hardware setting although this [post](https://docs.nvidia.com/cuda/gpudirect-rdma/index.html#supported-systems) suggests that GPU-single CPU/IOH-NIC works but yields worse performance. What I didn't anticipate is that the performance can get this much worse. So does it mean that  GPU-to-NIC connection has to be PXB/PIX/NV to get GPU Direct RDMA work?
I will also try with NCCL_P2P_LEVEL and see if it improves multi-GPU training on single machine.

**Comment by sjeaugey** [comment]
Also the way your Ethernet switch is configured can matter a lot when it comes to RoCE performance. Setting the ethernet switch in lossless mode, i.e. to not drop packets (a.k.a. flow control or PFC) is quite critical, otherwise performance can quickly drop to a few MB/s (very similar to your first screenshot).

**Comment by AddyLaddy** [comment]
Closing old issues. Please open another one if you are still seeing issues.
