### ISSUE TITLE
bus bandwidth seems slightly off for all_gather

### ISSUE THREAD

**Issue by christopherhesse** [NVIDIA/nccl-tests#45]
According to https://github.com/NVIDIA/nccl-tests/blob/master/doc/PERFORMANCE.md#allgather:

```
algbw = S/t
busbw = algbw * (n-1)/n
```

According to the code: https://github.com/NVIDIA/nccl-tests/blob/master/src/all_gather.cu#L50

```
algbw = S/t * (n-1)/n
busbw = algbw
```

Am I reading the code correctly? Seems like either the code or the document is incorrect.

I think the same issue may exist for reduce_scatter.

**Comment by sjeaugey** [comment]
Seems you're right. I'll fix it.

**Comment by sjeaugey** [comment]
So it turns out that busbw was correct, but algbw was already embedding the (nranks-1)/nranks factor.

And the definition of "algorithm bandwidth" for allgather (and reducescatter) is subject to interpretation : when you perform an allgather (especially in place) on N ranks, you're really asking to just receive N-1 chunks.

Now indeed that wasn't consistent with the documentation nor the way we compute it for other collective operations, so it's fixed now.

**Comment by christopherhesse** [comment]
Sorry, my example was confusing, I meant `busbw = S/t * (n-1)/n`.  And yeah, as long as the code matches the docs or vice versa, it means my comparisons will match nccl-tests.  Thanks for fixing it!

**Comment by sjeaugey** [comment]
Actually your description was entirely correct -- it just took me some time to understand what we did and why (that was quite a long time ago and prior to when the documentation was written).
