### ISSUE TITLE
Questions about the function BenchTime()

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl-tests#84]
Hi,

I have read the nccl-tests code, and a little confused about BenchTime() function:
1. why run once startColl() before the real test ? and about the comment "// Sync" above it , what does it mean ?
2. why run once more before doing data check ? why not just use the result, which was generated right now ?

Thanks

**Comment by sjeaugey** [comment]
1. `startColl/completeColl` should absorb any GPU desync that would exist prior to calling BenchTime. So if a GPU is late, after that first call, all GPUs should be re-synchronized.
2. For data check we need to first [initialize](https://github.com/NVIDIA/nccl-tests/blob/master/src/common.cu#L433) the input and output data and then call the operation only once, then check the result is correct. That's why we have a separate call for data check.
