### ISSUE TITLE
Topology XML file

### ISSUE THREAD

**Issue by guntrogu** [NVIDIA/nccl-tests#86]
Hi,

I would like to set the NCCL_TOPO_FILE to a valid value before running all_reduce_perf script.
What is the correct location for this file, or should I generate it ?

Thanks!

**Comment by sjeaugey** [comment]
Why would you like to set this file?

The `NCCL_TOPO_FILE` is usually generated by the VM provider so you should not need to generate it yourself, and the VM provider should document where to find this file.

Now if you're running your own VM, then indeed you may want to dump the XML topology on the baremetal system (`NCCL_TOPO_DUMP_FILE=system.xml`), keep only the `<cpu>` and `<pci>` tags (remove the `<gpu>` and `<nic>`), then inject it inside the VM using `NCCL_TOPO_FILE`), provided the PCI IDs are the same inside the VM and on baremetal, otherwise you'll have to adjust the PCI bus IDs to match what's inside the VM.

**Comment by AddyLaddy** [comment]
No further feedback so I'll close this issue. Please open another one if you are still seeing issues.

**Comment by alokprasad** [comment]
@AddyLaddy   if i want to generate topology of multi-node ( 4 node)  setup ( each running single T600 single gpu on single NIC cx5) all four connected via switch , is there way to generate combine topology.
if i run nccl-tests ( using mpirun) the  NCCL_GRAPH_DUMP_FILE   only dumps master topo

**Comment by kiskra-nvidia** [comment]
You can set `NCCL_GRAPH_DUMP_FILE_RANK` to the rank that is to generate the file (by default it's rank `0`). So in your setup, you will want to run the application multiple times, with different `NCCL_GRAPH_DUMP_FILE_RANK` values in each run.

P.S. Please do not add new questions to closed issues. Open new issues instead.
